params:
  algo:
    name: a2c_continuous
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 2.0
    e_clip: 0.2
    entropy_coef: 0.0
    env_name: isaacgym
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 32
    kl_threshold: 0.008
    learning_rate: 3e-4
    lr_schedule: adaptive
    max_epochs: 10
    mini_epochs: 5
    minibatch_size: 16384
    mixed_precision: true
    multi_gpu: false
    name: PoppyHumanoid
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    num_actors: 64
    ppo: true
    reward_shaper:
      scale_value: 1.0
    save_best_after: 100
    save_frequency: 100
    score_to_win: 20000
    seq_len: 4
    tau: 0.95
    truncate_grads: true
    value_bootstrap: true
  load_checkpoint: false
  load_path: ''
  model:
    name: continuous_a2c_logstd
  network:
    mlp:
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 512
      - 256
      - 128
    name: actor_critic
    separate: false
    space:
      continuous:
        fixed_sigma: true
        mu_activation: None
        mu_init:
          name: default
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0.0
  seed: 42
